version: "3.7"

services:
  app_proxy:
    environment:
      APP_HOST: pnex-polkadot
      APP_PORT: 80
      PROXY_AUTH_ADD: "false"

  polkadot:
    container_name: polkadot
    image: parity/polkadot
    restart: unless-stopped
    ports:
      - ${APP_POLKADOT_PORT_P2P}:30333 # p2p port
      - ${APP_POLKADOT_PORT_RPC}:9933 # rpc port
      - ${APP_POLKADOT_PORT_WS}:9944 # ws port
      - ${APP_POLKADOT_PORT_PROMETHEUS}:9615 # prom port
    volumes:
      -  ${APP_DATA_DIR}:/polkadot
    command: [
      "--chain", "${APP_POLKADOT_CHAIN}",
      "--unsafe-rpc-external",
      "--rpc-cors", "all",
      "--prometheus-external",
      "--database", "auto",
      "--sync", "warp",
      "--pruning=256", "--unsafe-pruning",
    ]
    networks:
      default:
        ipv4_address: $APP_POLKADOT_NODE_IP

  pnex-polkadot:
    depends_on: [polkadot]
    restart: unless-stopped
    container_name: pnex-polkadot
    image: chevdor/polkadot-node-explorer
    environment:
      - PNEX_WS_URL=ws://$APP_POLKADOT_NODE_IP:$APP_POLKADOT_PORT_WS
      - PNEX_NODE_IP=$APP_POLKADOT_NODE_IP
      - PNEX_PROMETHEUS_PORT=$APP_POLKADOT_PORT_PROMETHEUS
      - PNEX_PROMETHEUS_METRICS=metrics
      - PNEX_POOL_TIME=2000
    networks:
      default:
        ipv4_address: $APP_POLKADOT_PNEX_IP
