version: "3.7"

services:
  app_proxy:
    environment:
      APP_HOST: $APP_POLKADOT_NODE_IP
      APP_PORT: 17080
      PROXY_AUTH_WHITELIST: "/api/*"

  polkadot:
    container_name: polkadot
    image: parity/polkadot
    ports:
      - 30333:30333 # p2p port
      - 9933:9933 # rpc port
      - 9944:9944 # ws port
    volumes:
      -  ${APP_DATA_DIR}:/polkadot
    command: [
      "--name", "Polkadot",
      "--unsafe-rpc-external",
      "--rpc-cors", "all"
    ]
  polkadotjs:
    container_name: polkadotjs
    image: jacogr/polkadot-js-apps
    environment:
      - WS_URL=ws://$APP_POLKADOT_NODE_IP:9944
    ports:
      - 17080:80
