version: "3.7"

services:
  app_proxy:
    environment:
      APP_HOST: pnex-polkadot
      APP_PORT: 80

  polkadot:
    container_name: polkadot
    image: parity/polkadot
    ports:
      - ${APP_POLKADOT_PORT_P2P}:30333 # p2p port
      - ${APP_POLKADOT_PORT_RPC}:9933 # rpc port
      - ${APP_POLKADOT_PORT_WS}:9944 # ws port
    volumes:
      -  ${APP_DATA_DIR}:/polkadot
    command: [
      "--chain", "${APP_POLKADOT_CHAIN}",
      "--unsafe-rpc-external",
      "--rpc-cors", "all",
      "--prometheus-external",
      "--database", "auto",
      "--sync", "warp",
      "--prometheus-port", "${APP_POLKADOT_PORT_PROMETHEUS}"
    ]

  pnex-polkadot:
    container_name: pnex-polkadot
    image: wirednkod13/polkadot-node-explorer
    environment:
      - PNEX_WS_URL=ws://$APP_POLKADOT_NODE_IP:$APP_POLKADOT_PORT_WS
      - PNEX_NODE_IP=$APP_POLKADOT_NODE_IP
      - PNEX_PROMETHEUS_PORT=$APP_POLKADOT_PORT_PROMETHEUS
      - PNEX_PROMETHEUS_METRICS=metrics
      - PNEX_POOL_TIME=2000
