version: "3.7"

services:
  app_proxy:
    environment:
      APP_HOST: pnex-westend
      APP_PORT: 80
      PROXY_AUTH_ADD: "false"

  westend:
    container_name: westend
    image: parity/polkadot
    ports:
      - ${APP_WESTEND_PORT_P2P}:30333 # p2p port
      - ${APP_WESTEND_PORT_RPC}:9933 # rpc port
      - ${APP_WESTEND_PORT_WS}:9944 # ws port
      - ${APP_WESTEND_PORT_PROMETHEUS}:9615 # prom port
    volumes:
      - ${APP_DATA_DIR}:/polkadot
    command: [
      "--chain", "${APP_WESTEND_CHAIN}",
      "--unsafe-rpc-external",
      "--rpc-cors", "all",
      "--prometheus-external",
      "--database", "auto",
      "--sync", "warp",
      "--state-pruning=256", "--blocks-pruning=1024",
    ]
    networks:
      default:
        ipv4_address: $APP_WESTEND_NODE_IP

  pnex-westend:
    container_name: pnex-westend
    image: chevdor/polkadot-node-explorer
    environment:
      - PNEX_WS_URL=ws://$APP_WESTEND_NODE_IP:$APP_WESTEND_PORT_WS
      - PNEX_NODE_IP=10.211.55.20
      - PNEX_PROMETHEUS_PORT=$APP_WESTEND_PORT_PROMETHEUS
      - PNEX_PROMETHEUS_METRICS=metrics
      - PNEX_POOL_TIME=2000
    networks:
      default:
        ipv4_address: $APP_WESTEND_PNEX_IP
