version: "3.7"

services:
  app_proxy:
    environment:
      APP_HOST: pnex-kusama
      APP_PORT: 80

  kusama:
    container_name: kusama
    image: parity/polkadot
    ports:
      - ${APP_KUSAMA_PORT_P2P}:30333 # p2p port
      - ${APP_KUSAMA_PORT_RPC}:9933 # rpc port
      - ${APP_KUSAMA_PORT_WS}:9944 # ws port
    volumes:
      - ${APP_DATA_DIR}:/polkadot
    command: [
      "--chain", "${APP_KUSAMA_CHAIN}",
      "--unsafe-rpc-external",
      "--rpc-cors", "all",
      "--prometheus-external",
      "--database", "auto",
      "--sync", "warp",
      "--prometheus-port", "${APP_KUSAMA_PORT_PROMETHEUS}"
    ]
    networks:
      default:
        ipv4_address: $APP_KUSAMA_NODE_IP

  pnex-kusama:
    container_name: pnex-kusama
    image: chevdor/polkadot-node-explorer
    environment:
      - PNEX_WS_URL=ws://$APP_KUSAMA_NODE_IP:$APP_KUSAMA_PORT_WS
      - PNEX_NODE_IP=$APP_KUSAMA_NODE_IP
      - PNEX_PROMETHEUS_PORT=$APP_KUSAMA_PORT_PROMETHEUS
      - PNEX_PROMETHEUS_METRICS=metrics
      - PNEX_POOL_TIME=2000
    networks:
      default:
        ipv4_address: $APP_KUSAMA_PNEX_IP
