version: "3.7"

services:
  kusama:
    container_name: kusama
    image: parity/polkadot
    ports:
      - ${APP_KUSAMA_PORT_P2P}:30333 # p2p port
      - ${APP_KUSAMA_PORT_RPC}:9933 # rpc port
      - ${APP_KUSAMA_PORT_WS}:9944 # ws port
    volumes:
      - ${APP_DATA_DIR}:/polkadot
    command: [
      "--chain", "${APP_KUSAMA_CHAIN}",
      "--unsafe-rpc-external",
      "--rpc-cors", "all",
      "--prometheus-external",
      "--database", "auto",
      "--sync", "warp",
      "--prometheus-port", "${APP_KUSAMA_PORT_PROMETHEUS}"
    ]
  node-explorer:
    container_name: kusama-nodex
    image: wirednkod13/polkadot-node-explorer
    environment:
      - WS_URL=ws://$APP_POLKADOT_NODE_IP:9944
    ports:
      - 17091:80
