version: "3.7"

services:
  polkadot:
    container_name: kusama
    image: parity/polkadot
    ports:
      - ${APP_KUSAMA_PORT_P2P}:30333 # p2p port
      - ${APP_KUSAMA_PORT_RPC}:9933 # rpc port
      - ${APP_KUSAMA_PORT_WS}:9944 # ws port
    volumes:
      - ${APP_DATA_DIR}:/polkadot
    command: [
      "--chain", "${APP_KUSAMA_CHAIN}",
      "--unsafe-rpc-external",
      "--rpc-cors", "all",
      "--prometheus-external",
      "--database", "auto",
      "--sync", "warp",
      "--prometheus-port", "${APP_KUSAMA_PORT_PROMETHEUS}"
    ]
