version: "3.7"

services:
  # app_proxy:
  #   environment:
  #     APP_HOST: polkadotjs_polkadotjs_1
  #     APP_PORT: 17081
  #     PROXY_AUTH_WHITELIST: "/api/*"

  polkadotjs:
    container_name: polkadotjs
    image: jacogr/polkadot-js-apps
    environment:
      - WS_URL=ws://$APP_POLKADOT_NODE_IP:9944
    ports:
      - 17080:80
